# Generated by Django 6.0.2 on 2026-02-27 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('doktor', 'Doktor'), ('hemşire', 'Hemşire'), ('yönetici', 'Yönetici'), ('bakici', 'Hasta Bakıcı')], default='Hemsire', max_length=20, verbose_name='Rol / Ünvan')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
