# Generated by Django 6.0.2 on 2026-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='rol',
            field=models.CharField(choices=[('doktor', 'Doktor'), ('hemşire', 'Hemşire'), ('yönetici', 'Yönetici')], default='Hemsire', max_length=20, verbose_name='Rol / Ünvan'),
        ),
    ]
