# Generated by Django 6.0.2 on 2026-05-01 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_alter_profil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Mesaj İçeriği')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('okundu_mu', models.BooleanField(default=False)),
                ('acil_mi', models.BooleanField(default=False, verbose_name='Acil Durum Mesajı mı?')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
