# Generated by Django 6.0.2 on 2026-02-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Açık Adres')),
                ('kan_grubu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kan Grubu')),
                ('kronik_hastaliklar', models.TextField(blank=True, null=True, verbose_name='Kronik Hastalıklar')),
                ('alerjiler', models.TextField(blank=True, null=True, verbose_name='Alerjiler')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
            },
        ),
    ]
