# Generated by Django 6.0.2 on 2026-05-01 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Açık Adres')),
                ('kan_grubu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kan Grubu')),
                ('kronik_hastaliklar', models.TextField(blank=True, null=True, verbose_name='Kronik Hastalıklar')),
                ('alerjiler', models.TextField(blank=True, null=True, verbose_name='Alerjiler')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
            },
        ),
        migrations.CreateModel(
            name='HastaIlac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=100, verbose_name='İlaç Adı')),
                ('kutu_ici_adet', models.IntegerField(default=0, verbose_name='Kutudaki Toplam Hap Sayısı')),
                ('gunluk_kullanim_miktari', models.IntegerField(default=1, verbose_name='Günde Kaç Adet İçiyor?')),
                ('kutu_acilis_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Kutuyu Açtığı Tarih')),
                ('doz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doz Bilgisi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Kullanıma Devam Ediyor mu?')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilaclar', to='hastalar.hasta', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Hasta İlacı',
                'verbose_name_plural': 'Hasta İlaçları',
            },
        ),
    ]
