# Generated by Django 6.0.2 on 2026-03-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HastaIlaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=100, verbose_name='İlaç Adı')),
                ('kullanim_dozu', models.CharField(max_length=50, verbose_name='Kullanım Dozu (Örn: Günde 2 Tok)')),
                ('baslangic_tarihi', models.DateField(auto_now_add=True)),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Hâlâ kullanıyor mu?')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilaclar', to='hastalar.hasta', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Hasta İlacı',
                'verbose_name_plural': 'Hasta İlaçları',
            },
        ),
    ]
