# Generated by Django 6.0.2 on 2026-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hastailac',
            name='acilis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Kutu Açılış Tarihi'),
        ),
    ]
