# Generated by Django 6.0.2 on 2026-05-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalar', '0002_hastailac_acilis_tarihi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IslemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_ozeti', models.CharField(max_length=200, verbose_name='İşlem Özeti')),
                ('detay', models.TextField(verbose_name='Sistem Arka Plan Detayları (Sadece Dr/Yön)')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='hastalar.hasta')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
            },
        ),
    ]
