# Generated by Django 6.0.2 on 2026-03-18 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalar', '0002_hastailaci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastailaci',
            name='baslangic_tarihi',
        ),
        migrations.RemoveField(
            model_name='hastailaci',
            name='kullanim_dozu',
        ),
        migrations.AddField(
            model_name='hastailaci',
            name='gunluk_kullanim_miktari',
            field=models.IntegerField(default=1, verbose_name='Günde Kaç Adet İçiyor?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hastailaci',
            name='kutu_acilis_tarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kutuyu Açtığı Tarih'),
        ),
        migrations.AddField(
            model_name='hastailaci',
            name='kutu_ici_adet',
            field=models.IntegerField(default=1, verbose_name='Kutudaki Toplam Hap Sayısı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hastailaci',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Kullanıma Devam Ediyor mu?'),
        ),
        migrations.AlterField(
            model_name='hastailaci',
            name='ilac_adi',
            field=models.CharField(max_length=100, verbose_name='İlaç Adı (Örn: Parol 500mg)'),
        ),
    ]
