# Generated by Django 6.0.2 on 2026-02-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ziyaretler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Malzeme Adi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açiklama')),
                ('stok_miktari', models.PositiveIntegerField(default=0, verbose_name='Stok Miktari')),
                ('birim', models.CharField(max_length=20, verbose_name='Birim (Adet, Kutu, Litre vb.)')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
            },
        ),
        migrations.CreateModel(
            name='ZiyaretMalzemeKullanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanilan_miktar', models.PositiveIntegerField(verbose_name='Kullanılan Miktar')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.malzeme', verbose_name='Kullanılan Malzeme')),
                ('ziyaret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziyaretler.ziyaret', verbose_name='İlgili Ziyaret')),
            ],
            options={
                'verbose_name': 'Kullanılan Malzeme',
                'verbose_name_plural': 'Kullanılan Malzemeler',
            },
        ),
    ]
