# Generated by Django 6.0.2 on 2026-02-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hastalar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziyaret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziyaret_tarihi', models.DateTimeField(verbose_name='Ziyaret Tarihi')),
                ('yapilan_islemler', models.TextField(verbose_name='Yapılan İşlemler')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], max_length=20)),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hastalar.hasta', verbose_name='Hasta')),
                ('personel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Ziyaret',
                'verbose_name_plural': 'Ziyaretler',
            },
        ),
    ]
