# Generated by Django 6.0.2 on 2026-03-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalar', '0003_remove_hastailaci_baslangic_tarihi_and_more'),
        ('ziyaretler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiyaretIlacKontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemsirenin_saydigi_adet', models.IntegerField(verbose_name='Kutuda Kalan Sayı')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hastalar.hastailaci', verbose_name='Kontrol Edilen İlaç')),
                ('ziyaret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilac_kontrolleri', to='ziyaretler.ziyaret')),
            ],
            options={
                'verbose_name': 'İlaç Kontrolü',
                'verbose_name_plural': 'İlaç Kontrolleri',
            },
        ),
    ]
