# Generated by Django 6.0.2 on 2026-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziyaretler', '0002_ziyaretilackontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziyaret',
            name='islem_tipi',
            field=models.CharField(choices=[('muayene', 'Genel Muayene'), ('pansuman', 'Pansuman / Yara Bakımı'), ('ilac_takip', 'İlaç Takibi & Kör Sayım'), ('enjeksiyon', 'Enjeksiyon / Serum')], default='muayene', max_length=50, verbose_name='İşlem Tipi'),
        ),
        migrations.AddField(
            model_name='ziyaret',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Görev Notları'),
        ),
        migrations.AlterField(
            model_name='ziyaret',
            name='durum',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='planlandi', max_length=20),
        ),
        migrations.AlterField(
            model_name='ziyaret',
            name='yapilan_islemler',
            field=models.TextField(blank=True, null=True, verbose_name='Yapılan İşlemler'),
        ),
    ]
